options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-west2"
  _AR_REPO: "recycling-images"
  _IMAGE_NAME: "backend"
  _DEPLOY_REGION: "us-west2"

steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "Backend"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud deploy releases create "be-${SHORT_SHA}" \
          --region="${_DEPLOY_REGION}" \
          --delivery-pipeline="backend-pipeline" \
          --skaffold-file="Deploy/Backend/skaffold.yaml" \
          --source="." \
          --images="backend-image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}"