apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recycling-backend-dev
spec:
  template:
    spec:
      serviceAccountName: backend-run-dev@cs5224-grp7-3bb27.iam.gserviceaccount.com
      containers:
        - image: backend-image
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "cs5224-grp7-3bb27"
            - name: ML_PREDICT_URL
              value: "https://recycling-ml-dev-306363185631.us-west2.run.app/predict"