apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recycling-ml-dev
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
          autoscaling.knative.dev/metric: "cpu"        # Scale based on CPU, not requests
          autoscaling.knative.dev/target: "70"         # The 0.7 CPU threshold you wanted
          autoscaling.knative.dev/minScale: "0"         # ML is expensive; 0 is okay if backend handles retries
          autoscaling.knative.dev/maxScale: "5"
          run.googleapis.com/cpu-throttling: "false"   # CPU always on (prevents inference lag)
    spec:
      serviceAccountName: backend-run-dev@cs5224-grp7-3bb27.iam.gserviceaccount.com
      containerConcurrency: 2
      containers:
        - image: ml-image
          resources:
              limits:
                cpu: "1"
                memory: "2Gi"   # Required for model weights/tensors
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "cs5224-grp7-3bb27"