apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recycling-frontend-prod
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0" # Scale back to 0 when idle to save costs
        autoscaling.knative.dev/maxScale: "10" 
        autoscaling.knative.dev/target: "60" # Starts scaling when ~60 requests are active
    spec:
      serviceAccountName: frontend-run-prod@cs5224-grp7-3bb27.iam.gserviceaccount.com
      containerConcurrency: 100 # Set higher concurrency for production to handle more requests per instance; low cost, high concurrent user capacity
      containers:
        - image: frontend-image
          resources:
            limits:
              cpu: "1000m" # 1 vCPU
              memory: "512Mi"
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://recycling-backend-prod-REPLACE_ME.run.app"
            - name: NEXT_PUBLIC_USE_MOCK_API
              value: "false"
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              value: "REPLACE_ME"
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              value: "REPLACE_ME"
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              value: "REPLACE_ME"
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              value: "REPLACE_ME"
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              value: "REPLACE_ME"
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              value: "REPLACE_ME"