apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: recycling-frontend-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3" 
        autoscaling.knative.dev/target: "50"
    spec:
      serviceAccountName: frontend-run-dev@cs5224-grp7-3bb27.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
        - image: frontend-image
          resources:
            limits:
              cpu: "1000m" # 1 vCPU
              memory: "512Mi"
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://recycling-backend-dev-306363185631.asia-southeast1.run.app"
            - name: NEXT_PUBLIC_USE_MOCK_API
              value: "false"
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              value: "AIzaSyAM95gmG6aIkX9YPlkks-0i7lx49wnjvH8"
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              value: "cs5224-grp7-3bb27.firebaseapp.com"
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              value: "cs5224-grp7-3bb27"
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              value: "cs5224-grp7-3bb27.firebasestorage.app"
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              value: "306363185631"
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              value: "1:306363185631:web:d9cdd06f7fdb535416ec6a"